### Verbo GET - Listar Todos
GET http://localhost:8000/produto/ HTTP/1.1

### Verbo GET - Listar Um
GET http://localhost:8000/produto/10 HTTP/1.1

### Verbo POST - Adicionar
POST http://localhost:8000/produto/ HTTP/1.1
Content-Type: application/json

{
  "nome": "Produto do FELIPE MORTARI",
  "descricao": "Descrição do Produto A",
  "foto": "link_da_foto.jpg",
  "valor_unitario": 19
}

### Verbo PUT - Atualizar
PUT http://localhost:8000/produto/2 HTTP/1.1
Content-Type: application/json

{
  "nome": "Produto NOVO DO FELIPE",
  "descricao": "Descrição atualizada do Produto B",
  "foto": "link_da_foto_atualizada.jpg",
  "valor_unitario": 29
}

### Verbo DELETE - Excluir
DELETE http://localhost:8000/produto/3 HTTP/1.1


