
### Verbo GET – listar todos
GET http://localhost:8000/cliente/ HTTP/1.1
### Verbo GET – listar um
GET http://localhost:8000/cliente/10 HTTP/1.1
### Verbo POST – adicionar
POST http://localhost:8000/cliente/ HTTP/1.1
Content-Type: application/json

{
  "nome": "John Doe",
  "cpf": "12345678901",
  "telefone": "555-555-5555"
}
### Verbo PUT – atualiza
PUT http://localhost:8000/cliente/2 HTTP/1.1
Content-Type: application/json

{
  "nome": "Jane Doe",
  "cpf": "98765432109",
  "telefone": "555-555-5555"
}
### Verbo DELETE - excluir
DELETE http://localhost:8000/cliente/3 HTTP/1.1
